Add res for git hooks
    Delete df file
m-C02WQ3H4HTD5:Secretfy-config-creator s0s0249$ clear
Add res files for git hooks. It contains the following files :-

- exclude/info : Info file for excluding from git.
- hooks/pre-commit : pre-commit script which is invoked when any commit is
  pushed.
- hooks/heimdall.py : This is invoked by pre-commit which then run the heimdall
  tool for scanning.

diff --git a/secretfy_template/res/heimdall/hooks/pre-commit b/secretfy_template/res/heimdall/hooks/pre-commit
--- a/secretfy_template/res/heimdall/hooks/pre-commit
+++ b/secretfy_template/res/heimdall/hooks/pre-commit
@@ -1,10 +1,11 @@
-echo "PRE-COMMIT MESSAGE >>>>"
 file_name=$(git diff --cached --name-only --diff-filter=ACM)
-echo ":::::::File name is: " $PWD " -- " $file_name
-diff=$(git diff --cached $file_name | tail -n +6)
-#diff=$( git diff --cached $file_name )
-#echo "Difference: "$diff
-#output=$( python .git/hooks/my_commit.py )
-output=$( secretfy -scan $PWD $file_name )
-echo "This is value: "$output
-exit 1
+python3 .git/hooks/heimdall.py $PWD $file_name
+output=$?
+#if [ ! -z "$output" -a "$output" != " " ]
+#then
+#  echo "Successfully executed script"
+#else
+#  # Redirect stdout from echo command to stderr.
+#  echo "Script exited with error." >&2
+#fi
+exit $output
